package com.github.guilhermesgb.steward.utils;

import com.joanzapata.iconify.Icon;

public enum FontAwesomeRegular implements Icon {

    fa_r_hand_lizard('\uf258'),
    fa_r_smile('\uf118'),
    fa_r_times_circle('\uf057'),
    fa_r_check_circle('\uf058'),
    fa_r_paper_plane('\uf1d8'),
    fa_r_clock('\uf017'),
    fa_r_sun('\uf185'),
    fa_r_clipboard('\uf328'),
    fa_r_file_alt('\uf15c'),
    fa_r_meh('\uf11a'),
    fa_r_file_image('\uf1c5'),
    fa_r_calendar_times('\uf273'),
    fa_r_eye_slash('\uf070'),
    fa_r_hospital('\uf0f8'),
    fa_r_envelope('\uf0e0'),
    fa_r_window_restore('\uf2d2'),
    fa_r_flag('\uf024'),
    fa_r_folder('\uf07b'),
    fa_r_address_card('\uf2bb'),
    fa_r_heart('\uf004'),
    fa_r_life_ring('\uf1cd'),
    fa_r_moon('\uf186'),
    fa_r_map('\uf279'),
    fa_r_object_ungroup('\uf248'),
    fa_r_clone('\uf24d'),
    fa_r_check_square('\uf14a'),
    fa_r_envelope_open('\uf2b6'),
    fa_r_keyboard('\uf11c'),
    fa_r_hand_point_right('\uf0a4'),
    fa_r_edit('\uf044'),
    fa_r_square('\uf0c8'),
    fa_r_caret_square_right('\uf152'),
    fa_r_closed_captioning('\uf20a'),
    fa_r_calendar_plus('\uf271'),
    fa_r_hand_peace('\uf25b'),
    fa_r_file_pdf('\uf1c1'),
    fa_r_arrow_alt_circle_up('\uf35b'),
    fa_r_folder_open('\uf07c'),
    fa_r_user('\uf007'),
    fa_r_bookmark('\uf02e'),
    fa_r_window_maximize('\uf2d0'),
    fa_r_copy('\uf0c5'),
    fa_r_calendar_check('\uf274'),
    fa_r_calendar_minus('\uf272'),
    fa_r_comment_alt('\uf27a'),
    fa_r_bell_slash('\uf1f6'),
    fa_r_id_card('\uf2c2'),
    fa_r_play_circle('\uf144'),
    fa_r_snowflake('\uf2dc'),
    fa_r_registered('\uf25d'),
    fa_r_futbol('\uf1e3'),
    fa_r_question_circle('\uf059'),
    fa_r_file_excel('\uf1c3'),
    fa_r_copyright('\uf1f9'),
    fa_r_file_powerpoint('\uf1c4'),
    fa_r_stop_circle('\uf28d'),
    fa_r_circle('\uf111'),
    fa_r_file_archive('\uf1c6'),
    fa_r_compass('\uf14e'),
    fa_r_address_book('\uf2b9'),
    fa_r_gem('\uf3a5'),
    fa_r_arrow_alt_circle_down('\uf358'),
    fa_r_money_bill_alt('\uf3d1'),
    fa_r_calendar('\uf133'),
    fa_r_hourglass('\uf254'),
    fa_r_user_circle('\uf2bd'),
    fa_r_hand_paper('\uf256'),
    fa_r_credit_card('\uf09d'),
    fa_r_file_video('\uf1c8'),
    fa_r_arrow_alt_circle_right('\uf35a'),
    fa_r_comment('\uf075'),
    fa_r_bell('\uf0f3'),
    fa_r_list_alt('\uf022'),
    fa_r_caret_square_down('\uf150'),
    fa_r_trash_alt('\uf2ed'),
    fa_r_hdd('\uf0a0'),
    fa_r_object_group('\uf247'),
    fa_r_newspaper('\uf1ea'),
    fa_r_hand_point_left('\uf0a5'),
    fa_r_file_word('\uf1c2'),
    fa_r_hand_point_down('\uf0a7'),
    fa_r_calendar_alt('\uf073'),
    fa_r_sticky_note('\uf249'),
    fa_r_chart_bar('\uf080'),
    fa_r_lightbulb('\uf0eb'),
    fa_r_handshake('\uf2b5'),
    fa_r_minus_square('\uf146'),
    fa_r_arrow_alt_circle_left('\uf359'),
    fa_r_save('\uf0c7'),
    fa_r_frown('\uf119'),
    fa_r_hand_pointer('\uf25a'),
    fa_r_plus_square('\uf0fe'),
    fa_r_id_badge('\uf2c1'),
    fa_r_file_code('\uf1c9'),
    fa_r_window_minimize('\uf2d1'),
    fa_r_images('\uf302'),
    fa_r_comments('\uf086'),
    fa_r_thumbs_up('\uf164'),
    fa_r_image('\uf03e'),
    fa_r_caret_square_left('\uf191'),
    fa_r_share_square('\uf14d'),
    fa_r_thumbs_down('\uf165'),
    fa_r_hand_rock('\uf255'),
    fa_r_window_close('\uf410'),
    fa_r_dot_circle('\uf192'),
    fa_r_pause_circle('\uf28b'),
    fa_r_caret_square_up('\uf151'),
    fa_r_file('\uf15b'),
    fa_r_star_half('\uf089'),
    fa_r_lemon('\uf094'),
    fa_r_file_audio('\uf1c7'),
    fa_r_star('\uf005'),
    fa_r_hand_spock('\uf259'),
    fa_r_building('\uf1ad'),
    fa_r_hand_scissors('\uf257'),
    fa_r_hand_point_up('\uf0a6');

    char character;

    private FontAwesomeRegular(char character) {
        this.character = character;
    }

    public String key() {
        return this.name().replace('_', '-');
    }

    public char character() {
        return this.character;
    }

}
